// <auto-generated />
namespace Autovivi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class brandModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(brandModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201611021822358_brandModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
